name: Generate Apps List

on:
  push:
    branches:
      - main

jobs:
  generate-apps-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Generate Apps List
        id: generate-apps-list
        run: |
          app_list=""
          for app_folder in Apps/*; do
            if [ -f "$app_folder/app.json" ]; then
              app_data=$(cat "$app_folder/app.json")
              app_name=$(echo "$app_data" | jq -r .app)
              app_description=$(echo "$app_data" | jq -r .description)
              app_image=$(echo "$app_data" | jq -r .image)
              app_tag=$(echo "$app_data" | jq -r .tag)

              app_list+="| $app_name | $app_image | $app_tag | $app_description | <br />"
            fi
          done

          echo "::set-output name=content::${app_list}"

      - name: Append App List to README.md
        run: |
          app_list="${{ steps.generate-apps-list.outputs.content }}"
          echo "${app_list}" >> README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with apps list"
          git push --set-upstream origin ${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
